export const CONFIG = {
    PINECONE_API_KEY: process.env.PINECONE_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    PINECONE_ENVIRONMENT: process.env.PINECONE_ENVIRONMENT,
    PINECONE_INDEX_NAME: process.env.PINECONE_INDEX_NAME,
    INDEX_INIT_TIMEOUT: process.env.INDEX_INIT_TIMEOUT,
    PORT: process.env.PORT,
};